### ISSUE TITLE
Publishing ARC doesn't work

### ISSUE THREAD

**Issue by SabrinaZander** [nfdi4plants/archigator-frontend#5]
I wanted to publish an ARC, and all pipelines were passed. After I clicked Publish ARC, I was redirected to the DataPLANT Publication Service. All metadata is correctly displayed. However, when I press the Publish button, it spins for several minutes and nothing happens.
![Screenshot 2024-07-16 1007162](https://github.com/user-attachments/assets/794590d1-68a2-4b02-afce-2dbc6a78f521)

**Comment by Zerskk** [comment]
Bugfix: arc-summary.md was removed and task was renamed in pipeline, so that archigator couldnt find the files.

**Comment by SabrinaZander** [comment]
Thank you for the quick help. The ARC has now been published but of course the data from the arc-summary.md is now missing in the overview of the publication (https://archive.nfdi4plants.org/records/wr9ps-fmv73) . That's also inconvenient, or? How should this be handled in the future? Or have I done something wrong?

**Comment by Zerskk** [comment]
The summary is not generated at the moment and has be be included in the pipeline. At the moment it is removed from Archigator until it is inlcuded in the Gitlab pipeline again.
