### ISSUE TITLE
NFDI4Plants Archive shows many 404 errors

### ISSUE THREAD

**Issue by Hannah-Doerpholz** [nfdi4plants/archigator-frontend#9]
When I got to one of our ARCs with a DOI to the [https://archive.nfdi4plants.org/records/30cpm-z1c67](https://archive.nfdi4plants.org/records/30cpm-z1c67), and then try to navigate anywhere from the menu bar at the top, I always get a 404 error message. Is it supposed to be like that? We should probably link to the correct webpages here too. In the screenshots below I accessed the link above and then clicked on `About -> Our Mission`. The menu bar also seems to not be the same as the new webpage anymore. I'm not sure if this is an archigator issue or homepage issue though.

![grafik](https://github.com/user-attachments/assets/6fa5f94d-ea30-4314-b157-70b7ab3ce8c8)

![grafik](https://github.com/user-attachments/assets/925fe08b-cf83-45de-a395-6801e7daa42c)

**Comment by Freymaurer** [comment]
The archive website is not part of the nfdi4plants main website in this repository. I am not sure who the maintainer of the archive website is. But the navbar in use is the deprecated web-component. Thats why the navbar forwards to dead links.

**Comment by Brilator** [comment]
I guess the ARChigator needs to update web components? @Zerskk

**Comment by Zerskk** [comment]
web component support was dropped, thats why i removed the navbar on top

**Comment by Zerskk** [comment]
i also removed the navbar from the error pages

**Comment by Brilator** [comment]
Hi @Zerskk, but the outdated navbar is still there? https://archive.nfdi4plants.org

**Comment by Zerskk** [comment]
@j-bauer The navbar in Invenio has to be removed.

**Comment by j-bauer** [comment]
This will be removed tomorrow during the maintenance.
